services:
  frontend:
    build: frontend
    ports:
      - "80:80"
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PG_URI=postgres://postgres:secret@database/postgres
    ports:
      - "3000:3000"
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck: 
      interval: 5s
      test: 'pg_isready --username=postgres'
    volumes:
      - ./data:/var/lib/postgresql
